using System;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace AIShaderCreator.Editor
{
    public static class VFXCodeWriter
    {
        private const string ScriptFolder = "Assets/GeneratedVFX/_scripts";

        public static string Write(string effectMethodBody, out string className)
        {
            EnsureFolders();

            className = "VFXGen_" + DateTime.Now.Ticks;
            var scriptPath = $"{ScriptFolder}/{className}.cs";
            var fullPath = Path.Combine(Application.dataPath, "..", scriptPath)
                              .Replace('/', Path.DirectorySeparatorChar);

            File.WriteAllText(fullPath, BuildScript(effectMethodBody, className, scriptPath), Encoding.UTF8);
            AssetDatabase.Refresh();
            return scriptPath;
        }

        private static string BuildScript(string body, string className, string scriptPath)
        {
            // インデントを揃える
            var indented = new StringBuilder();
            foreach (var line in body.Split('\n'))
                indented.Append("        ").AppendLine(line.TrimEnd());

            return $@"// Auto-generated by AI Shader Creator - do not edit
using UnityEngine;
using UnityEditor;

[InitializeOnLoad]
public static class {className}
{{
    static {className}()
    {{
        EditorApplication.delayCall += Execute;
    }}

    static void Execute()
    {{
        try
        {{
            CreateEffect();
        }}
        catch (System.Exception e)
        {{
            Debug.LogError(""[AI Effect Creator] 生成エラー: "" + e.Message + ""\n"" + e.StackTrace);
        }}

        // スクリプト自身を削除
        var path = ""{scriptPath.Replace("\\", "/")}"";
        EditorApplication.delayCall += () =>
        {{
            if (File.Exists(Path.Combine(Application.dataPath, "".."", path)))
                AssetDatabase.DeleteAsset(path);
        }};
    }}

    static void CreateEffect()
    {{
{indented}
    }}
}}
";
        }

        private static void EnsureFolders()
        {
            if (!AssetDatabase.IsValidFolder("Assets/GeneratedVFX"))
                AssetDatabase.CreateFolder("Assets", "GeneratedVFX");
            if (!AssetDatabase.IsValidFolder(ScriptFolder))
                AssetDatabase.CreateFolder("Assets/GeneratedVFX", "_scripts");
        }
    }
}
