using System;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace AIShaderCreator.Editor
{
    public static class VFXCodeWriter
    {
        private const string ScriptFolder = "Assets/GeneratedVFX/_scripts";

        public static string Write(string effectMethodBody, out string className, string fixedPrefabPath = null)
        {
            EnsureFolders();

            className = "VFXGen_" + DateTime.Now.Ticks;
            var scriptPath = $"{ScriptFolder}/{className}.cs";
            var fullPath = Path.Combine(Application.dataPath, "..", scriptPath)
                              .Replace('/', Path.DirectorySeparatorChar);

            // 編集モード時: GenerateUniqueAssetPath を固定パスに置換
            var codeToWrite = fixedPrefabPath != null
                ? InjectFixedPath(effectMethodBody, fixedPrefabPath)
                : effectMethodBody;

            File.WriteAllText(fullPath, BuildScript(codeToWrite, className, scriptPath), Encoding.UTF8);
            VFXAutoFixer.Register(codeToWrite, className);

            // プレハブパスを SessionState に記録（編集追跡用）
            if (fixedPrefabPath != null)
                VFXAutoFixer.SetExpectedPrefabPath(fixedPrefabPath);
            else
                ExtractAndStoreExpectedPath(codeToWrite);

            AssetDatabase.Refresh();
            return scriptPath;
        }

        private static void ExtractAndStoreExpectedPath(string code)
        {
            // GenerateUniqueAssetPath の引数からベース名を抽出
            var match = System.Text.RegularExpressions.Regex.Match(
                code, @"GenerateUniqueAssetPath\s*\(\s*""([^""]+)""\s*\)");
            if (match.Success)
                VFXAutoFixer.SetExpectedPrefabPath(match.Groups[1].Value);
        }

        private static string InjectFixedPath(string code, string fixedPath)
        {
            var escaped = fixedPath.Replace("\\", "/");
            // AssetDatabase.GenerateUniqueAssetPath(...) → "fixedPath"
            return System.Text.RegularExpressions.Regex.Replace(
                code,
                @"AssetDatabase\.GenerateUniqueAssetPath\s*\([^)]+\)",
                $"\"{escaped}\"");
        }

        private static string BuildScript(string body, string className, string scriptPath)
        {
            // インデントを揃える
            var indented = new StringBuilder();
            foreach (var line in body.Split('\n'))
                indented.Append("        ").AppendLine(line.TrimEnd());

            return $@"// Auto-generated by AI Shader Creator - do not edit
using UnityEngine;
using UnityEditor;

[InitializeOnLoad]
public static class {className}
{{
    static {className}()
    {{
        EditorApplication.delayCall += Execute;
    }}

    static void Execute()
    {{
        try
        {{
            CreateEffect();
        }}
        catch (System.Exception e)
        {{
            Debug.LogError(""[AI Effect Creator] 生成エラー: "" + e.Message + ""\n"" + e.StackTrace);
        }}

        // スクリプト自身を削除
        var path = ""{scriptPath.Replace("\\", "/")}"";
        EditorApplication.delayCall += () =>
        {{
            if (File.Exists(Path.Combine(Application.dataPath, "".."", path)))
                AssetDatabase.DeleteAsset(path);
        }};
    }}

    static void CreateEffect()
    {{
{indented}
    }}
}}
";
        }

        private static void EnsureFolders()
        {
            if (!AssetDatabase.IsValidFolder("Assets/GeneratedVFX"))
                AssetDatabase.CreateFolder("Assets", "GeneratedVFX");
            if (!AssetDatabase.IsValidFolder(ScriptFolder))
                AssetDatabase.CreateFolder("Assets/GeneratedVFX", "_scripts");
        }
    }
}
